---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plaincooking-helm.fullname" . }}-secret
  labels:
    {{- include "plaincooking-helm.labels" . | nindent 4 }}
stringData:
  PLAINCOOKING_DATABASE_FILENAME: /var/lib/plaincooking/plaincooking.sqlite
  PLAINCOOKING_DATABASE_JOURNALMODE: wal
  {{- with .Values.plaincooking }}
  {{- with .logging }}
  PLAINCOOKING_LOGGING_LEVEL: {{ .level | quote }}
  {{- end }}
  {{- with .oidc }}
  PLAINCOOKING_OIDC_ISSUER: {{ .issuer | quote }}
  PLAINCOOKING_OIDC_CLIENT_ID: {{ .client.id | quote }}
  PLAINCOOKING_OIDC_CLIENT_SECRET: {{ .client.secret | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.ingress }}
  {{- $scheme := empty .tls | ternary "http" "https" }}
  {{- $host := first .hosts }}
  PLAINCOOKING_OIDC_REDIRECT_URL: {{ urlJoin (dict "scheme" $scheme "host" $host.host "path" "/oauth2/callback") }}
  {{- end }}
