name: CI

on:
  push:
    branches:
      - master
      - feat/*
      - ci/*
    pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build
        run: make

      - name: Test Go
        run: go test -race ./...

      - name: Lint Go
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Lint Typescript
        working-directory: frontend
        run: npm run lint

      - name: Lint Svelte
        working-directory: frontend
        run: npm run check
